# Generated by Django 2.0.3 on 2018-04-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_auto_20180423_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=50, null=True)),
                ('belong', models.CharField(blank=True, max_length=50, null=True)),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
