# Generated by Django 2.0.3 on 2018-04-25 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_auto_20180424_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='user_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='under_blog', to='firstapp.User'),
        ),
    ]
