# Generated by Django 2.0.4 on 2018-05-03 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_auto_20180425_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='editors_choice',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='blog',
            name='news_choice',
            field=models.NullBooleanField(),
        ),
    ]
